### PR TITLE
Implement OTIO version as part of the matrix strategy

### LINKED ISSUE #7: Add OTIO version to matrix in CI
Refactor the ci.yml file to include otio versions in the matrix to test the plugin against desired versions.

### PR DESCRIPTION
**Pull request by apetrynet**
resolves #7 

- Added OTIO version to the matrix 
- Added windows-latest to the os matrix
- Added more python versions to python matrix 

Updated table formatting in README.md

### CODE REVIEW

**Review by JeanChristopheMorinPerso — COMMENTED** [review]
That's great @apetrynet . Should we also test against tip of main?

**Comment by apetrynet** [comment]
Finally found the "exclude" syntax in the matrix and all tests pass.
Python 3.11 will only test against "main"

**Review by JeanChristopheMorinPerso — APPROVED** [review]
Looks good to me!

**Comment by apetrynet** [comment]
Thank you @JeanChristopheMorinPerso for all your help!

**Pull request merged**
